#!/bin/sh
# Build a throwaway example project with two layers and print a Markdown
# walkthrough of it (commands, output and every file sich generates).
# Regenerate the committed copy with: pnpm run docs:example
set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
TMP=$(mktemp -d)
TMP_REAL=$(cd "$TMP" && pwd -P)
trap 'rm -rf "$TMP"' EXIT

# Deterministic output: isolated git config, fixed identity and dates, no colors.
export GIT_CONFIG_NOSYSTEM=1 GIT_CONFIG_GLOBAL="$TMP/gitconfig" NO_COLOR=1
export GIT_AUTHOR_NAME=You GIT_AUTHOR_EMAIL=you@example.com
export GIT_COMMITTER_NAME=You GIT_COMMITTER_EMAIL=you@example.com
export GIT_AUTHOR_DATE=2026-01-01T12:00:00Z GIT_COMMITTER_DATE=2026-01-01T12:00:00Z
printf '[init]\n\tdefaultBranch = main\n[advice]\n\tdetachedHead = false\n' >"$GIT_CONFIG_GLOBAL"

# `sich` (and the pre-commit hook) run this checkout's build.
mkdir "$TMP/bin"
printf '#!/bin/sh\nexec node "%s/dist/cli.js" "$@"\n' "$ROOT" >"$TMP/bin/sich"
chmod +x "$TMP/bin/sich"
export PATH="$TMP/bin:$PATH"
unset SICH_BIN 2>/dev/null || true

# Show temp paths as ~ so the output reads like a real home folder.
tidy() { sed -e "s|$TMP_REAL|~|g" -e "s|$TMP|~|g"; }
# Print a command (written with ~/ for the temp folder) and its output as a
# console session. eval runs in this shell, so a `cd` carries over.
run() {
  printf '$ %s\n' "$*"
  eval "$(printf '%s' "$*" | sed "s|~/|$TMP/|g")" >"$TMP/.out" 2>&1 || true
  tidy <"$TMP/.out"
}
console() { printf '```console\n'; for cmd in "$@"; do run "$cmd"; done; printf '```\n\n'; }
# Print a file (or only sich's managed block of it).
file() { printf '`%s`\n\n```text\n' "$1"; tidy <"$1"; printf '```\n\n'; }
block() { printf '`%s` (sich block)\n\n```text\n' "$1"; sed -n '/>>> sich/,/<<< sich/p' "$1" | tidy; printf '```\n\n'; }

# Remotes: the public base repo and one private repo per layer.
mkdir -p "$TMP/remotes"
for r in myproject myproject-personal myproject-team; do git init -q --bare "$TMP/remotes/$r.git"; done

# An ordinary project, already pushed to its public remote.
PROJ="$TMP/myproject"
mkdir -p "$PROJ/src"
cd "$PROJ"
git init -q
printf '# myproject\n' >README.md
printf 'console.log("hello");\n' >src/app.js
git add -A && git commit -q -m "initial commit"
git remote add origin "$TMP/remotes/myproject.git"
git push -q -u origin main 2>/dev/null

# The private files from the README's Quickstart.
printf '# My notes\n\n- ask the team about the release date\n' >my-notes.md
printf '# Roadmap\n\n- Q1: ship layers\n' >roadmap.md
printf 'API_KEY=not-a-real-key\n' >api-keys.env
mkdir -p llm-transcripts
printf '# Planning chat\n\n...\n' >llm-transcripts/2026-01-01-planning.md

cat <<'EOF'
# Example: the Quickstart, step by step

This is the README's Quickstart run for real, with every command's output and
every file sich generates. It was generated by
[`scripts/make-example.sh`](../scripts/make-example.sh) (`pnpm run docs:example`).

The only difference: instead of `--gh` creating private GitHub repos, the layers
get local remotes. `~/remotes/` stands in for GitHub: `myproject.git` is the
public repo, `myproject-personal.git` and `myproject-team.git` are the private
ones.

`~/myproject` starts as an ordinary repo with `README.md` and `src/app.js`,
pushed to its public remote. It also has a few files that shouldn't be public:
`my-notes.md`, `roadmap.md`, `api-keys.env` and `llm-transcripts/`.

## 1. A personal layer, just for you

EOF

console "sich init" \
  "sich new personal --remote ~/remotes/myproject-personal.git" \
  "sich claim personal my-notes.md" \
  'sich personal commit -m "adding notes"' \
  "sich push personal"

printf '## 2. A team layer, shared with your team\n\n'
console "sich new team --remote ~/remotes/myproject-team.git" \
  "sich claim team roadmap.md api-keys.env llm-transcripts/" \
  "sich status -v"
printf '`sich commit` commits base and every layer with changes at once (here only\n'
printf '`team` has any), and `sich push` pushes them all:\n\n'
console 'sich commit -m "adding team files"' "sich push"

printf '## 3. What each repo sees\n\n'
printf 'All files in the folder (git data folders collapsed):\n\n```text\n'
find . -mindepth 1 \( -path ./.git -o -path ./.sich/personal -o -path ./.sich/team \) -prune -print -o -print |
  sed 's|^\./||' | sort | while read -r p; do
    if [ -d "$p" ]; then echo "$p/"; else echo "$p"; fi
  done
printf '```\n\n'
printf 'Plain `git` only sees base files, and the public remote never learns the private file names:\n\n'
console "git status" "git ls-files" "git -C ~/remotes/myproject.git ls-tree -r --name-only main"
printf 'Each layer tracks only its own claims plus its claims list:\n\n'
console "sich personal ls-files" "sich team ls-files" "sich which api-keys.env"

printf '## 4. The files sich generates\n\n'
printf 'Claims lists, tracked by their own layer so collaborators get them:\n\n'
file .sich/personal.paths
file .sich/team.paths
printf 'Base hides `.sich/` and every claim. This file lives in `.git/` and is never pushed:\n\n'
block .git/info/exclude
printf 'Each layer ignores everything except its own claims:\n\n'
block .sich/personal/info/exclude
block .sich/team/info/exclude
printf 'The pre-commit hook that guards base:\n\n'
file .git/hooks/pre-commit

printf '## 5. The guard in action\n\n'
printf 'Forcing a private file into base gets blocked:\n\n'
console "git add -f my-notes.md" 'git commit -m "oops"' "git restore --staged my-notes.md"

printf '## 6. A collaborator joins\n\n'
printf 'A collaborator with access to `myproject-team` (but not `myproject-personal`)\n'
printf 'clones base and attaches the `team` layer:\n\n'
mkdir -p "$TMP/collaborator"
cd "$TMP/collaborator"
console "git clone -q ~/remotes/myproject.git && cd myproject" \
  "sich attach team ~/remotes/myproject-team.git" \
  "ls -A" "sich status"
printf 'They get `roadmap.md`, `api-keys.env` and `llm-transcripts/`, but `my-notes.md`\n'
printf 'never reaches them, and nothing tells them a `personal` layer exists.\n'
