#!/bin/sh
# Build a throwaway example project with two layers and print a Markdown
# walkthrough of it (commands, output and every file sich generates).
# Regenerate the committed copy with: pnpm run docs:example
set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
TMP=$(mktemp -d)
TMP_REAL=$(cd "$TMP" && pwd -P)
trap 'rm -rf "$TMP"' EXIT

# Deterministic output: isolated git config, fixed identity and dates, no colors.
export GIT_CONFIG_NOSYSTEM=1 GIT_CONFIG_GLOBAL="$TMP/gitconfig" NO_COLOR=1
export GIT_AUTHOR_NAME=You GIT_AUTHOR_EMAIL=you@example.com
export GIT_COMMITTER_NAME=You GIT_COMMITTER_EMAIL=you@example.com
export GIT_AUTHOR_DATE=2026-01-01T12:00:00Z GIT_COMMITTER_DATE=2026-01-01T12:00:00Z
printf '[init]\n\tdefaultBranch = main\n[advice]\n\tdetachedHead = false\n' >"$GIT_CONFIG_GLOBAL"

# `sich` (and the pre-commit hook) run this checkout's build.
mkdir "$TMP/bin"
printf '#!/bin/sh\nexec node "%s/dist/cli.js" "$@"\n' "$ROOT" >"$TMP/bin/sich"
chmod +x "$TMP/bin/sich"
export PATH="$TMP/bin:$PATH"
unset SICH_BIN 2>/dev/null || true

# Show temp paths as ~ so the output reads like a real home folder.
tidy() { sed -e "s|$TMP_REAL|~|g" -e "s|$TMP|~|g"; }
# Print a command (written with ~/ for the temp folder) and its output as a
# console session. eval runs in this shell, so a `cd` carries over.
run() {
  printf '$ %s\n' "$*"
  eval "$(printf '%s' "$*" | sed "s|~/|$TMP/|g")" >"$TMP/.out" 2>&1 || true
  tidy <"$TMP/.out"
}
console() { printf '```console\n'; for cmd in "$@"; do run "$cmd"; done; printf '```\n\n'; }
# Print a file (or only sich's managed block of it).
file() { printf '`%s`\n\n```text\n' "$1"; tidy <"$1"; printf '```\n\n'; }
block() { printf '`%s` (sich block)\n\n```text\n' "$1"; sed -n '/>>> sich/,/<<< sich/p' "$1" | tidy; printf '```\n\n'; }

# Remotes: the public base repo and one private repo per layer.
mkdir -p "$TMP/remotes"
for r in myproject myproject-notes myproject-keys; do git init -q --bare "$TMP/remotes/$r.git"; done

# An ordinary project, already pushed to its public remote.
PROJ="$TMP/myproject"
mkdir -p "$PROJ/src"
cd "$PROJ"
git init -q
printf '# myproject\n' >README.md
printf 'console.log("hello");\n' >src/app.js
git add -A && git commit -q -m "initial commit"
git remote add origin "$TMP/remotes/myproject.git"
git push -q -u origin main 2>/dev/null

cat <<'EOF'
# Example: one project, two private layers

This walkthrough was generated by [`scripts/make-example.sh`](../scripts/make-example.sh)
(`pnpm run docs:example`), so every command and output below is real. `~/remotes/`
stands in for GitHub: `myproject.git` is the public repo, `myproject-notes.git`
and `myproject-keys.git` are private ones (with `--gh`, sich would create those
on GitHub instead).

`~/myproject` starts as an ordinary repo with `README.md` and `src/app.js`,
pushed to its public remote.

## 1. Set up two layers

`notes` is just for you; `keys` is shared with your team.

EOF

console "sich init" \
  "sich new notes --remote ~/remotes/myproject-notes.git" \
  "sich new keys --remote ~/remotes/myproject-keys.git"

printf '## 2. Claim private files\n\n'
mkdir -p roadmap
printf '# Notes\n\n- ask the team about the release date\n' >NOTES.md
printf '# Q1\n\n- ship layers\n' >roadmap/q1.md
printf 'API_KEY=not-a-real-key\n' >.env
printf 'console.log("hello, world");\n' >src/app.js
printf 'Write `NOTES.md`, `roadmap/q1.md` and `.env`, and edit `src/app.js`, then:\n\n'
console "sich add notes NOTES.md roadmap/" "sich add keys .env" "sich status -v"

printf '## 3. Commit and push everything\n\n'
printf '`sich commit` commits base and every layer with changes; `sich push` pushes them all.\n\n'
console 'sich commit -m "add notes, roadmap and keys"' "sich push"

printf '## 4. What each repo sees\n\n'
printf 'All files in the folder (git data folders collapsed):\n\n```text\n'
find . -mindepth 1 \( -path ./.git -o -path ./.sich/notes -o -path ./.sich/keys \) -prune -print -o -print |
  sed 's|^\./||' | sort | while read -r p; do
    if [ -d "$p" ]; then echo "$p/"; else echo "$p"; fi
  done
printf '```\n\n'
printf 'Plain `git` only sees base files, and the public remote never learns the private file names:\n\n'
console "git status" "git ls-files" "git -C ~/remotes/myproject.git ls-tree -r --name-only main"
printf 'Each layer tracks only its own claims plus its claims list:\n\n'
console "sich notes ls-files" "sich keys ls-files" "sich which .env"

printf '## 5. The files sich generates\n\n'
printf 'Claims lists, tracked by their own layer so collaborators get them:\n\n'
file .sich/notes.paths
file .sich/keys.paths
printf 'Base hides `.sich/` and every claim. This file lives in `.git/` and is never pushed:\n\n'
block .git/info/exclude
printf 'Each layer ignores everything except its own claims:\n\n'
block .sich/notes/info/exclude
block .sich/keys/info/exclude
printf 'The pre-commit hook that guards base:\n\n'
file .git/hooks/pre-commit

printf '## 6. The guard in action\n\n'
printf 'Forcing a private file into base gets blocked:\n\n'
console "git add -f NOTES.md" 'git commit -m "oops"' "git restore --staged NOTES.md"

printf '## 7. A teammate joins\n\n'
printf 'A teammate with access to `myproject-keys` (but not `myproject-notes`) clones base and attaches the `keys` layer:\n\n'
mkdir -p "$TMP/teammate"
cd "$TMP/teammate"
console "git clone -q ~/remotes/myproject.git && cd myproject" \
  "sich attach keys ~/remotes/myproject-keys.git" \
  "ls -A" "sich status"
printf 'They get `.env`, but `NOTES.md` and `roadmap/` never reach them, and nothing\n'
printf 'tells them a `notes` layer exists.\n'
